version: "3"
services:
  senaite:
    image: ramonski/senaite:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 2G
    ports:
      - "8080:8080"
    environment:
      SITE: "senaite"
