version: "3.9"

services:

  zeo:
    image: senaite/senaite:edge
    command: zeo
    volumes:
      - ./data:/data

  instance1:
    image: senaite/senaite:edge
    ports:
      - 8081:8080
    links:
      - zeo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500MB
    environment:
      ZEO_ADDRESS: "zeo:8080"

  instance2:
    image: senaite/senaite:edge
    ports:
      - 8082:8080
    links:
      - zeo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500MB
    environment:
      ZEO_ADDRESS: "zeo:8080"

volumes:
  data:
    external: true
